//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person_Age
    {
        public int Person_Age_Id { get; set; }
        public System.DateTime DateBirth { get; set; }
    }
}
